### ISSUE TITLE
Documentação

### ISSUE THREAD

**Issue by JockaMt** [RiquelmeMagal/esp32_monitor#1]
Quais bibliotecas python foram usadas nesse projeto?

**Comment by RiquelmeMagal** [comment]
> Quais bibliotecas python foram usadas nesse projeto?

Oi, o projeto ainda está em desenvolvimento, mas preferi já upar o que está funcionando por enquanto. Mais tarde irei dar continuidade pra tentar fazer uma documentação decente.

1. Estou utilizando a ESP32 + DHT11 como um WebServer, no qual ele cria um HTML simples com umidade e temperatura somente, tudo isso via Wi-Fi. Alguma das bibliotecas que estão sendo utilizadas na IDE do Arduino são: WiFi, WebServer, ESPmDNS, DHTesp, Serial, MDNS  
2. No Python estou utilizando Flask pra criar um "servidor web", e usando Requests para fazer a requisição, a biblioteca time para que seja atualizado a cada n segundos, a threading que faz o papel de atualizar em segundo plano, e a QT foi algo opcional mas é funcional, no vídeo que vi como base ele utilizava. (como dito anteriormente ainda irei fazer uma documentação, e nessa documentação terá os devidos créditos ao criador do código fonte).
[Monitor de temperatura e umidade com ESP8266 e interface gráfica em python
](https://www.youtube.com/watch?v=45VCTB7f0sM).

Ainda considero esse projeto uma gambiarra, o HTML não está legal.
Se caso precisar da foto da montagem da ESP32 na protoboad me avise.
